#!/bin/bash

set -e

not_installed() {
  ! command -v $1 > /dev/null 2>&1
}

bosh_errand_resource_dir=$(realpath $(dirname $(dirname $0)))

if not_installed bundle; then
  echo "# bundler is not installed! run the following command:"
  echo "    gem install bundler --no-document"
  exit 1
fi

cd $bosh_errand_resource_dir
bundle install
bundle exec rspec
